name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Build and assemble
        run: |
          python3 -m pip install poetry
          python3 -m poetry config virtualenvs.create false
          python3 -m poetry install --no-root
          python3 wrapper oneplus5t topaz
